language: elixir
elixir:
  - 1.3.0
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.2
  - 19.0
  - 19.2
addons:
  postgresql: "9.4"
sudo: false
before_script:
  - cd testapp/sample_telepathy
  - mix deps.get
  - mix ecto.setup.ci
  - cd ../..
script:
  - mix espec
  - cd testapp/sample_telepathy
  - mix espec
